# Generated by Django 5.2.3 on 2025-07-03 01:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_change_audio_file_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Frekansın ses dosyası (MP3, WAV vs.)', null=True, upload_to=api.models.frequency_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='audio_url',
            field=models.URLField(blank=True, help_text="Alternatif olarak harici ses URL'i (YouTube, SoundCloud vs.)", null=True),
        ),
    ]
