# Generated by Django 5.2.3 on 2025-07-03 01:09

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_audio_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='audio_url',
        ),
        migrations.AlterField(
            model_name='frequency',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Frekansın ses dosyası (sadece MP3 formatı)', null=True, upload_to=api.models.frequency_audio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
