# Generated by Django 5.2.3 on 2025-07-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_frequency_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfreport',
            name='content',
            field=models.TextField(default=2025, help_text='Rapor içeriği'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfreport',
            name='file_path',
            field=models.CharField(blank=True, help_text='Oluşturulan PDF dosyasının yolu', max_length=500, null=True),
        ),
    ]
